# Generated by Django 6.0.2 on 2026-03-15 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectrequest',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='message',
            field=models.TextField(default='', verbose_name='Сообщение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectrequest',
            name='phone',
            field=models.CharField(default='', max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
