# Generated by Django 6.0.2 on 2026-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_projectrequest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Оригинал')),
                ('thumbnail', models.ImageField(upload_to='gallery/thumbs/', verbose_name='Превью')),
            ],
        ),
    ]
