# Generated by Django 6.0.2 on 2026-03-16 12:36

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Фото'), ('video', 'Видео (YouTube)')], default='image', max_length=10, verbose_name='Тип')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=75, scale=None, size=[1200, 1200], upload_to='gallery/', verbose_name='Файл/Превью')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo', verbose_name='Ссылка на видео')),
                ('my_order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Объект галереи',
                'verbose_name_plural': 'Галерея',
                'ordering': ['my_order'],
            },
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
