# Generated by Django 6.0.2 on 2026-03-17 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_galleryimage_delete_galleryitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
