# Generated by Django 6.0.2 on 2026-03-19 21:15

import blog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_audiofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={'verbose_name': 'Аудиозапись', 'verbose_name_plural': 'Аудиозаписи'},
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(help_text='Допустимые форматы: mp3, wav, ogg. Макс. размер: 10 МБ.', upload_to='audio/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp3', 'wav', 'ogg']), blog.models.validate_file_size], verbose_name='Файл'),
        ),
    ]
