# Generated by Django 6.0.2 on 2026-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contactmessage_last_name_alter_contactmessage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
